- 👋 Hi, I’m @n3v3rdiegaming9000
- 👀 I’m interested in Minecraft and Making content
- 🌱 I’m currently learning how to make better content
- I also have a YT channel at https://www.youtube.com/c/N3V3RDIEGaming9000

<!---
n3v3rdiegaming9000/n3v3rdiegaming9000 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
